spring:
  application:
    name: agent-ai-users
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  messages:
    basename: lang/messages_en

server:
  port: 8082

client:
  url: http://localhost:4200

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000
  refresh-expiration-ms: 604800000